image: golang:1.17

stages:
  - build
  - upload

build:
  stage: build
  script:
    - go build ./...
    - /bin/bash generate-out.sh
    # Move to gitlab build directory
    - mv ./out/linux-arm64/epos-linux-arm64 ${CI_PROJECT_DIR}
    - mv ./out/linux-amd64/epos-linux-amd64 ${CI_PROJECT_DIR}
    - mv ./out/darwin-arm64/epos-darwin-arm64 ${CI_PROJECT_DIR}
    - mv ./out/darwin-amd64/epos-darwin-amd64 ${CI_PROJECT_DIR}
    - mv ./out/windows-arm64/epos-windows-arm64.exe ${CI_PROJECT_DIR}
    - mv ./out/windows-amd64/epos-windows-amd64.exe ${CI_PROJECT_DIR}
  artifacts:
    # instead of manually adding i.e. the built binaries, we can instead just
    # grab anything not tracked in Git
    untracked: true
    expire_in: 1 hour
    paths:
    - ./epos-linux-arm64
    - ./epos-linux-amd64
    - ./epos-darwin-arm64
    - ./epos-darwin-amd64
    - ./epos-windows-arm64.exe
    - ./epos-windows-amd64.exe

upload:
  stage: upload
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./out/linux-arm64/epos-linux-arm64 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/epos-open-source/linux/1.0.0/epos-linux-arm64"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./out/linux-amd64/epos-linux-amd64 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/epos-open-source/linux/1.0.0/epos-linux-amd64"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./out/darwin-arm64/epos-darwin-arm64 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/epos-open-source/darwin/1.0.0/epos-darwin-arm64"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./out/darwin-amd64/epos-darwin-amd64 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/epos-open-source/darwin/1.0.0/epos-darwin-amd64"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./out/darwin-arm64/epos-windows-arm64.exe "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/epos-open-source/windows/1.0.0/epos-windows-arm64.exe"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./out/darwin-amd64/epos-windows-amd64.exe "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/epos-open-source/windows/1.0.0/epos-windows-amd64.exe"'

