/*
    EPOS Open Source - Local installation with Docker
    Copyright (C) 2022  EPOS ERIC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
//file: ./cmd/structures.go
package cmd

type AutoGenerated struct {
	Version  string   
	Services Services 
	Volumes  Volumes  
	Networks Networks 
}
type Gui struct {
	Image         string   
	ContainerName string   
	Ports         []string 
	Environment   []string 
	Volumes       []string 
	Networks      []string 
	DependsOn     []string 
}
type Backofficegui struct {
	Image         string   
	ContainerName string   
	Ports         []string 
	Environment   []string 
	Volumes       []string 
	Networks      []string 
	DependsOn     []string 
}
type Gateway struct {
	Image         string   
	ContainerName string   
	Ports         []string 
	Networks      []string 
	Restart       string   
	Environment   []string 
}
type Rabbitmq struct {
	Image         string   
	ContainerName string   
	Ports         []string 
	Volumes       []string 
	Environment   []string 
	Networks      []string 
}
type Resources struct {
	Image         string   
	ContainerName string   
	Volumes       []string 
	Networks      []string 
	Restart       string   
	Ports         []string 
	Environment   []string 
	DependsOn     []string 
}
type Backoffice struct {
	Image         string   
	ContainerName string   
	Volumes       []string 
	Networks      []string 
	Restart       string   
	Ports         []string 
	Environment   []string 
	DependsOn     []string 
}
type Ingestor struct {
	Image         string   
	ContainerName string   
	Volumes       []string 
	Networks      []string 
	Restart       string   
	Environment   []string 
	DependsOn     []string 
}
type Externalaccess struct {
	Image         string   
	ContainerName string   
	Volumes       []string 
	Networks      []string 
	Restart       string   
	Ports         []string 
	Environment   []string 
	DependsOn     []string 
}
type Converter struct {
	Image         string   
	ContainerName string   
	Volumes       []string 
	Networks      []string 
	Restart       string   
	Environment   []string 
	DependsOn     []string 
}
type Processingaccessservice struct {
	Image         string   
	ContainerName string   
	Volumes       []string 
	Networks      []string 
	Restart       string   
	Ports         []string 
	Environment   []string 
	DependsOn     []string 
}
type Datametadataservice struct {
	Image         string   
	ContainerName string   
	Volumes       []string 
	Networks      []string 
	Restart       string   
	Environment   []string 
	DependsOn     []string 
}
type Postgrescerif struct {
	Restart       string   
	Image         string   
	ContainerName string   
	Environment   []string 
	Volumes       []string 
	Ports         []string 
	DependsOn     []string 
	Networks      []string 
}
type Metadatacache struct {
	Image         string   
	ContainerName string   
	Volumes       []string 
	Networks      []string 
	Restart       string   
	Environment   []string 
	DependsOn     []string 
}
type Services struct {
	Gui                     Gui                     
	Backofficegui           Backofficegui           
	Gateway                 Gateway                 
	Rabbitmq                Rabbitmq                
	Resources               Resources               
	Backoffice              Backoffice              
	Ingestor                Ingestor                
	Externalaccess          Externalaccess          
	Converter               Converter               
	Processingaccessservice Processingaccessservice 
	Datametadataservice     Datametadataservice     
	Postgrescerif           Postgrescerif           
	Metadatacache           Metadatacache           
}
type RabbitmqVolume struct {
	External bool 
}
type ResourcesVolume struct {
	External bool 
}
type BackofficeVolume struct {
	External bool 
}
type IngestorVolume struct {
	External bool 
}
type ExternalaccessVolume struct {
	External bool 
}
type ConverterVolume struct {
	External bool 
}
type DatametadataserviceVolume struct {
	External bool 
}
type ProcessingaccessserviceVolume struct {
	External bool 
}
type PsqldataVolume struct {
	External bool 
}
type Volumes struct {
	Rabbitmq                RabbitmqVolume                
	Resources               ResourcesVolume              
	Backoffice              BackofficeVolume              
	Ingestor                IngestorVolume                
	Externalaccess          ExternalaccessVolume          
	Converter               ConverterVolume               
	Datametadataservice     DatametadataserviceVolume     
	Processingaccessservice ProcessingaccessserviceVolume 
	Psqldata                PsqldataVolume                
}
type Networks struct {
	EposNetwork interface{} `yaml:"epos_network"`
}