name: "mirror"
on:
  push:
    branches:
      - main

jobs:
    deploy-me:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                  git remote add remote-repo https://github:${{secrets.GITLAB}}@epos-ci.brgm.fr/epos/opensource-docker.git
                  git checkout -b opensource-patch
                  git fetch --unshallow remote-repo
                  git push remote-repo opensource-patch